### This will be the solution to the Homework 4 of the subject CS 430 Introduction to Algorithm 

In [31]:
import numpy as np
import pandas as pd

#creating the A matrix based on the information given in the statement about the links between nodes
A = [[0, 0, 1, 0, 0, 1, 1, 0, 1, 0],
     [0, 0, 1, 0, 1, 0, 1, 0, 1, 0],
     [1, 1, 0, 0, 0, 0, 1, 0, 0, 0],
     [1, 0, 1, 0, 0, 0, 1, 0, 1, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 1, 0],
     [1, 0, 0, 1, 0, 0, 1, 0, 0, 0],
     [1, 0, 1, 0, 0, 0, 0, 0, 1, 0],
     [1, 0, 1, 0, 0, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [1, 0, 1, 0, 0, 0, 1, 0, 1, 0]]

A_matrix = []

for i in range(len(A)):
     row = [float(x) for x in A[i]] #converting the values on each row of the matrix into floats
     A_matrix.append(row) #creating a matrix based on the transformed rows

#A_matrix = np.array(A)
print(A_matrix)
type(A)

[[0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0], [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0], [1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0], [1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0], [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0], [1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0], [1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0], [1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0], [1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0]]


list

# (a) (1 point) 
### Find the row-normalized hyperlink matrix H of this graph. Are there any dangling nodes in this hyperlink graph?
### This function will serve to adapt the PageRank matrix into a Probability form

In [32]:
def prob(B: list) -> list: 
    rows = len(B)
    col = len(B[0])
    for i in range(rows):
        array = []
        for j in range(col):
            if (B[i][j] == 1.0):
                array.append(j) #saving the locations of the positions of thearray that are already filled 
        count = len(array)    
        for h in array:
            B[i][h] = round(B[i][h] / count, 2) #inserting the probability value into each of the previously filled position
    return B 

H_matrix = np.array(prob(A_matrix))

print(H_matrix)
print("\n")

[[0.   0.   0.25 0.   0.   0.25 0.25 0.   0.25 0.  ]
 [0.   0.   0.25 0.   0.25 0.   0.25 0.   0.25 0.  ]
 [0.33 0.33 0.   0.   0.   0.   0.33 0.   0.   0.  ]
 [0.25 0.   0.25 0.   0.   0.   0.25 0.   0.25 0.  ]
 [0.   0.   0.5  0.   0.   0.   0.   0.   0.5  0.  ]
 [0.33 0.   0.   0.33 0.   0.   0.33 0.   0.   0.  ]
 [0.33 0.   0.33 0.   0.   0.   0.   0.   0.33 0.  ]
 [0.33 0.   0.33 0.   0.   0.   0.   0.   0.33 0.  ]
 [0.   0.   0.   0.   0.   0.   1.   0.   0.   0.  ]
 [0.25 0.   0.25 0.   0.   0.   0.25 0.   0.25 0.  ]]




### The procedure to be followed in order to make the calculations will be to start from a solution vector and to iterate until a reasonable result is found.

In [33]:
length = max(H_matrix.shape)
print(length)

v = []
for i in range(length):
    v.append(round(1.0 / length, 2)) #setting up an initial v vector

reference = v   
threshold = 0.0000000001  
error = threshold + 0.1 
counter = 1
print("In the {} iteration: ".format(counter), v)

while(abs(error) > threshold): #iterating until the error gets lower than the threshold
    previous = v
    v = np.round(np.dot(v, H_matrix), 2)
    error = np.mean(v) - np.mean(previous)
    counter += 1
    print("\n")
    print("In the {}. iteration: ".format(counter), v)
    print("The error in the {}. iteration: ".format(counter), round(error, 4))

sum = np.mean(v) * len(v)
print("\n")
print(sum)
if (abs(sum -1.0) < 0.015): #checking if the vector fill the requirements for being a probability vector
    print("The v vector IS a probability vector")
else:
    print("The v vector IS NOT a probability vector")    
    

10
In the 1 iteration:  [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]


In the 2. iteration:  [0.18 0.03 0.22 0.03 0.02 0.02 0.27 0.   0.22 0.  ]
The error in the 2. iteration:  -0.001


In the 3. iteration:  [0.18 0.07 0.16 0.01 0.01 0.04 0.36 0.   0.16 0.  ]
The error in the 3. iteration:  0.0


0.99
The v vector IS a probability vector


### It can be seen that there is not any dangling node, due to the fact that there is not any null row within the H_matrix. That is to say, every single node has at least one outlink. When users reach a dangling node, they have nowhere to keep going and they stuck, for instance, like in a PDF document or image files. 

# (b) (2 points)
###  Find the Google matrix G of this graph. Assume the damping factor d=0.85. 


In [34]:
def damping(B:list, d:float) -> list:
    global reference
    rows = len(B)
    col = len(B[0])
    for i in range(rows): #reading each row
        list1 = [round(x * d, 3) for x in B[i]]
        #print(list1)
        list2 = [round(x * (1.0 - d), 3) for x in reference]
        #print(list2)
        for j in range(col):
            B[i][j] =  list1[j] + list2[j] #transforming each row by taking into account the damping factor
    return B 
    
#SHOULD WE HAVE TO TRANSFORM FROM H TO S? LE HE PREGUNTADO A CHLEBUS

print(H_matrix)

d = 0.85 #setting up a damping factor
G_matrix = damping(H_matrix, d)

print("\n")
print(G_matrix)
print("\n")
print(H_matrix)

#FUNCIONA MAL: WHY H_MATRIX TAKES THE VALUES OF G_MATRIX???????!!!!!!!!!!!!!!!!!!!

[[0.   0.   0.25 0.   0.   0.25 0.25 0.   0.25 0.  ]
 [0.   0.   0.25 0.   0.25 0.   0.25 0.   0.25 0.  ]
 [0.33 0.33 0.   0.   0.   0.   0.33 0.   0.   0.  ]
 [0.25 0.   0.25 0.   0.   0.   0.25 0.   0.25 0.  ]
 [0.   0.   0.5  0.   0.   0.   0.   0.   0.5  0.  ]
 [0.33 0.   0.   0.33 0.   0.   0.33 0.   0.   0.  ]
 [0.33 0.   0.33 0.   0.   0.   0.   0.   0.33 0.  ]
 [0.33 0.   0.33 0.   0.   0.   0.   0.   0.33 0.  ]
 [0.   0.   0.   0.   0.   0.   1.   0.   0.   0.  ]
 [0.25 0.   0.25 0.   0.   0.   0.25 0.   0.25 0.  ]]


[[0.015 0.015 0.227 0.015 0.015 0.227 0.227 0.015 0.227 0.015]
 [0.015 0.015 0.227 0.015 0.227 0.015 0.227 0.015 0.227 0.015]
 [0.295 0.295 0.015 0.015 0.015 0.015 0.295 0.015 0.015 0.015]
 [0.227 0.015 0.227 0.015 0.015 0.015 0.227 0.015 0.227 0.015]
 [0.015 0.015 0.44  0.015 0.015 0.015 0.015 0.015 0.44  0.015]
 [0.295 0.015 0.015 0.295 0.015 0.015 0.295 0.015 0.015 0.015]
 [0.295 0.015 0.295 0.015 0.015 0.015 0.015 0.015 0.295 0.015]
 [0.295 0.015 0.295 0.015 

# (c) (2 points) 
### You are NOT allowed to use the formula for the number of iterations (given in [1], page 15, item 2b) needed to obtain numerical values of the PageRank row vector v. Propose an alternative termination criterion for this iterative algorithm.

In [35]:
#tHE CRITERION THAT I USED IN A) WAS TO STOP WHEN THE ERROR WAS LOWER THAN THE THRESHOLD, SO THIS COULD BE THE ONE USED IN HERE, AND USE THE ONE DEFINED IN THE REPORT FOR A). THE ONE OF THE FORMULA loops = m/log10(1/d)

# (d) (4 points) 
### Find iteratively numerical values of all elements of the PageRank row vector v=[r(P1), r(P2),…, r(P10)]. Use your termination criterion proposed in item (c). How many iterations do you need to obtain your numerical results? Assume the damping factor d=0.85 and v(0)=[0.1, 0.1, 0.1,…, 0.1]. Implement this iterative algorithm by yourself (absolutely no Excel or program libraries)

# (e) (2 points) 
### Plot the evolution of numerical values of r(P5) and r(P7) for subsequent iteration steps of the algorithm for:  (e.1) d=0.55 and v(0)=[0.1, 0.1, 0.1,…, 0.1] (e.2) d=0.85 and v(0)=[0.1, 0.1, 0.1,…, 0.1]

# (f) (2 points) 
### Assume d=0.85 and run your algorithm for three different initial PageRank row vectors v1(0), v2(0) and v3(0). What are the final numerical values of v1, v2 and v3 ? Are they identicalor different?

# (g) (1 point) 
### Compare the numerical values of the PageRank row vector v for two different values of the damping factor d=0.85 and d=1. What is the basic difference between them? Explain it. 